#!/usr/bin/env python3
import os
import re
import sys
import tempfile
from datetime import datetime
from html import escape
from pathlib import Path
from urllib.parse import quote

# Exclusion patterns
EXCLUDE_PATTERNS = {
    '.git', 'node_modules', '.DS_Store', '__pycache__', '.env',
    'index.html',
    'style.css', 'template.html',
    'new-page.sh', 'new-page.py',
    '.gitignore', 'README.md'
}

# Content root; the optional first argument overrides it
DEFAULT_ROOT = '/var/www/html'

# Mirrors the backup-file rule in nginx.conf: what the server refuses to serve
# must not be advertised in a listing either
BACKUP_PATTERN = re.compile(r'(~|\.(bak|old|orig|save|swp|swo|tmp))$')

# Stamped into every generated index so an index.html somebody wrote by hand is
# never replaced by a listing. The second form recognises pages written by
# earlier versions of this script, which carried no marker.
GENERATED_MARKER = '<!-- generated by generator.py -->'
LEGACY_MARKER = '<table cellpadding=0 cellspacing=0 cols=3>'

def is_generated(path):
    """True if path is missing or is an index this script wrote itself"""
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            head = f.read(4096)
    except FileNotFoundError:
        return True
    except OSError:
        return False
    return GENERATED_MARKER in head or LEGACY_MARKER in head

def is_safe_path(path, root):
    """Verify path is within the content root"""
    try:
        resolved = Path(path).resolve()
        return resolved.is_relative_to(root)
    except (ValueError, RuntimeError, OSError):
        return False

def format_size(size):
    """Format file size in bytes to human readable format"""
    if size < 1024:
        return f"{size}B"
    elif size < 1024 * 1024:
        return f"{size // 1024}K"
    else:
        return f"{size // (1024 * 1024)}M"

def get_file_info(path):
    """Get file size and modification time"""
    stat = path.stat()
    size = stat.st_size
    mtime = datetime.fromtimestamp(stat.st_mtime).strftime('%Y-%m-%d')
    return format_size(size), mtime

def should_exclude(name):
    """Check if file/folder should be excluded"""
    return (name in EXCLUDE_PATTERNS
            or name.startswith('.')
            or BACKUP_PATTERN.search(name) is not None)

def link(name):
    """Return (href, text) for a directory entry, encoded for HTML output.

    Names come from the filesystem: quote() percent-encodes the URL so that #,
    ? and % cannot truncate the link target, escape() keeps the markup and the
    surrounding attribute intact.
    """
    return quote(name, safe=''), escape(name)

def generate_html(directory, root):
    """Generate index.html for a directory"""
    dir_path = Path(directory)
    
    # Get relative path from the content root
    rel_path = dir_path.relative_to(root)
    title = str(rel_path) + '/' if str(rel_path) != '.' else ''
    title_html = escape(title) if title else 'files/'
    
    # Collect entries
    folders = []
    files = []
    
    try:
        for item in sorted(dir_path.iterdir()):
            if should_exclude(item.name):
                continue
            
            # A link pointing outside the content root is neither ours to index
            # nor servable: listing it would only produce a dead entry
            if item.is_symlink() and not is_safe_path(item, root):
                print(f"Warning: skipping link outside the content root: {item}")
                continue
            
            if item.is_dir():
                _, mtime = get_file_info(item)
                folders.append((item.name, mtime))
            elif item.is_file():
                size, mtime = get_file_info(item)
                files.append((item.name, mtime, size))
    except PermissionError:
        pass
    
    # Generate HTML with embedded dark theme styles
    html = f"""<!DOCTYPE html>
{GENERATED_MARKER}
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style type="text/css">
* {{ margin: 0; padding: 0; font: inherit; color: inherit; box-sizing: border-box; }}
::selection {{ background: #ddd; color: #000 }}
:root {{ --lh: 1.5em }}
html {{ margin: 0 0 0 calc(100vw - 100%); -webkit-text-size-adjust: 100%; height: 100%; }}
body {{ font: 1em/var(--lh) monospace; padding: 16vh 2em 0; background: #f2f2f2; display: grid; grid: 1fr / minmax(auto, 64ch); justify-content: center; height: 100%; }}
a {{ display: inline-block; text-decoration: none; padding: .16666em; margin-left: -.16666em; }}
a i {{ border-bottom: 1px dotted }}
a:active i {{ border: none }}
footer {{ padding: calc(var(--lh) * 2) 0 8vh; display: flex; justify-content: space-between; align-items: center; }}
h1,p {{ margin-bottom: var(--lh); }}
table {{ border: none; margin-top: -.16666em }}
td:first-child {{ padding: 0 }}
td {{ padding: 0 3em }}
tr td:last-child {{ padding: 0}}
.theme-toggle {{ cursor: pointer; border: 1px solid #000; padding: 4px 8px; font-size: 0.9em; background: transparent; transition: all 0.2s; }}
.theme-toggle:hover {{ background: #ddd; }}

/* Dark theme */
body.dark {{ background: #1a1a1a; color: #e0e0e0; }}
body.dark ::selection {{ background: #333; color: #fff; }}
body.dark a i {{ border-color: #666; }}
body.dark .theme-toggle {{ border-color: #e0e0e0; }}
body.dark .theme-toggle:hover {{ background: #333; }}

@media (max-device-width: 600px) {{
  body {{ padding-top: 2em; justify-content: start }}
  footer {{ padding: 2em 0; flex-direction: column; gap: 1em; align-items: flex-start; }}
  a i {{ border-color: #888 }}
}}
</style>
<title>{title_html}</title>
</head>
<body>
<main>
<h1>{title_html}</h1>
<p>-</p>
<table cellpadding=0 cellspacing=0 cols=3>
<tbody>
"""
    
    # Add folders
    for name, mtime in folders:
        href, text = link(name)
        html += f'<tr><td><a href="{href}/"><i>{text}/</i></a><td><time>{mtime}</time><td align=right>-\n'
    
    # Add files
    for name, mtime, size in files:
        href, text = link(name)
        html += f'<tr><td><a href="{href}"><i>{text}</i></a><td><time>{mtime}</time><td align=right>{size}\n'
    
    html += """</table>
</main>
<footer>
<a href="../"><i>../</i></a>
<button class="theme-toggle" onclick="toggleTheme()">◐</button>
</footer>
<script>
function applyTheme() {
  document.body.classList.toggle('dark', location.hash === '#dark');
}

function toggleTheme() {
  location.hash = location.hash === '#dark' ? '' : '#dark';
  applyTheme();
}

window.addEventListener('hashchange', applyTheme);
applyTheme();
</script>
</body>
</html>"""
    
    return html

def generate_all(root_dir):
    """Generate index.html files for all directories"""
    root_path = Path(root_dir).resolve()
    
    if not root_path.is_dir():
        print(f"ERROR: {root_path} is not a directory")
        return
    
    for dirpath, dirnames, filenames in os.walk(root_path):
        # Filter out excluded directories
        dirnames[:] = [d for d in dirnames if not should_exclude(d)]
        
        current_dir = Path(dirpath)
        
        # Never write an index outside the content root, even if a directory is
        # swapped for a symlink while the walk is running
        if not is_safe_path(current_dir, root_path):
            print(f"WARNING: Skipping unsafe path: {current_dir}")
            continue
        
        # Generate single index.html with dark theme support
        html = generate_html(current_dir, root_path)
        index_file = current_dir / 'index.html'
        
        if not is_generated(index_file):
            print(f"Warning: {index_file} was written by hand, leaving it alone")
            continue
        
        try:
            # Write beside the index and rename it into place: a request landing
            # mid-generation must never see a truncated listing, and the rename
            # replaces a symlinked index.html instead of writing through it
            fd, tmp_name = tempfile.mkstemp(dir=current_dir, prefix='.index.html.', suffix='.tmp')
            try:
                with os.fdopen(fd, 'w', encoding='utf-8') as f:
                    f.write(html)
                
                # Readable by nginx, and owned like the directory it sits in so
                # that a bind-mounted content directory stays the host user's
                os.chmod(tmp_name, 0o644)
                dir_stat = current_dir.stat()
                os.chown(tmp_name, dir_stat.st_uid, dir_stat.st_gid)
                os.replace(tmp_name, index_file)
            except BaseException:
                os.unlink(tmp_name)
                raise
        except OSError as e:
            print(f"Warning: Could not write {index_file}: {e}")
            continue
        
        print(f"Generated index for: {current_dir}")

if __name__ == '__main__':
    print("Generating directory indexes...")
    generate_all(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_ROOT)
    print("Generation complete!")
