"""What the generator promises about the listings it writes."""
import os
import subprocess
import sys
import time
from pathlib import Path
from urllib.parse import unquote

import pytest

from conftest import REPO, generate, links, run_generator, serve


def entries(index):
    """Every listed entry except the ../ footer link."""
    return links(index)[:-1]


def test_encodes_names_so_every_link_resolves(content):
    listed = entries(content / 'index.html')
    names = sorted(p.name for p in content.iterdir() if p.name != 'index.html')

    assert sorted(text.rstrip('/') for _, text in listed) == names
    for href, text in listed:
        assert (content / unquote(href.rstrip('/'))).exists(), href
        assert unquote(href.rstrip('/')) == text.rstrip('/'), href

    hrefs = {href for href, _ in listed}
    assert 'g%23h.txt' in hrefs and 'i%3Fj.txt' in hrefs and '50%25.txt' in hrefs
    assert 'c%3Cd%3E.txt' in hrefs and '%22q%22.txt' in hrefs and 'sub%20dir/' in hrefs
    assert 'caf%C3%A9.txt' in hrefs


def test_listing_links_answer_over_http(content):
    with serve(content) as base_url:
        import urllib.error
        import urllib.request

        for href, _ in entries(content / 'index.html'):
            url = f'{base_url}/{href}'
            with urllib.request.urlopen(url, timeout=10) as response:
                assert response.status == 200, url


def test_hides_system_backup_and_own_files(tmp_path):
    root = tmp_path / 'html'
    root.mkdir()
    for name in ('keep.txt', 'notes.txt.bak', 'page.old', 'draft~', 'tmp.tmp', '.hidden'):
        (root / name).write_text('x')
    (root / 'style.css').write_text('x')
    (root / 'template.html').write_text('x')
    generate(root)

    listed = {text for _, text in entries(root / 'index.html')}
    assert listed == {'keep.txt'}, f'index.html itself must not be listed either: {listed}'


def test_keeps_a_hand_written_index(tmp_path):
    root = tmp_path / 'html'
    (root / 'custom').mkdir(parents=True)
    (root / 'custom' / 'index.html').write_text('<html>mine</html>\n')
    (root / 'custom' / 'page.txt').write_text('x')

    result = generate(root)
    generate(root)

    assert (root / 'custom' / 'index.html').read_text() == '<html>mine</html>\n'
    assert 'written by hand' in result.stdout
    assert f'Generated index for: {root / "custom"}' not in result.stdout


def test_replaces_indexes_written_by_older_versions(tmp_path):
    root = tmp_path / 'html'
    root.mkdir()
    (root / 'page.txt').write_text('x')
    generate(root)

    index = root / 'index.html'
    legacy = index.read_text().replace('<!-- generated by generator.py -->\n', '')
    index.write_text(legacy)
    generate(root)

    assert '<!-- generated by generator.py -->' in index.read_text()


def test_mirrors_the_nginx_backup_rule(tmp_path):
    sys.path.insert(0, str(REPO))
    import generator

    for name in ('notes.txt.bak', 'page.old', 'draft~', 'tmp.tmp', 'orig.orig', 'notes.swp'):
        assert generator.should_exclude(name), name
    for name in ('keep.txt', 'backup.BAK', 'page.html', 'notes.txt'):
        assert not generator.should_exclude(name), name


def test_never_writes_through_a_symlinked_index(tmp_path):
    root = tmp_path / 'html'
    (root / 'sub').mkdir(parents=True)
    victim = tmp_path / 'victim.txt'
    victim.write_text('ORIGINAL\n')
    os.symlink(victim, root / 'sub' / 'index.html')
    (root / 'sub' / 'inner.txt').write_text('x')
    (root / 'plain.txt').write_text('x')

    result = generate(root)

    assert victim.read_text() == 'ORIGINAL\n'
    assert (root / 'sub' / 'index.html').is_symlink()
    assert (root / 'index.html').exists()


def test_skips_links_that_point_outside_the_content_root(tmp_path):
    root = tmp_path / 'html'
    (root / 'real').mkdir(parents=True)
    (root / 'real' / 'page.txt').write_text('x')
    outside = tmp_path / 'outside'
    outside.mkdir()
    (outside / 'secret.txt').write_text('x')
    os.symlink(outside, root / 'linked')
    os.symlink(outside / 'secret.txt', root / 'linked-secret.txt')
    os.symlink(root / 'real' / 'page.txt', root / 'linked-page.txt')

    result = generate(root)

    listed = {text for _, text in entries(root / 'index.html')}
    assert 'linked/' not in listed and 'linked-secret.txt' not in listed
    assert 'linked-page.txt' in listed
    assert 'skipping link outside the content root' in result.stdout


def test_writes_complete_indexes_and_leaves_no_temporaries(tmp_path):
    root = tmp_path / 'html'
    (root / 'sub').mkdir(parents=True)
    for i in range(200):
        (root / f'f{i:03d}.txt').write_text('x')
    generate(root)

    for index in root.rglob('index.html'):
        text = index.read_text(encoding='utf-8')
        assert text.startswith('<!DOCTYPE html>')
        assert text.rstrip().endswith('</html>')
        assert '<!-- generated by generator.py -->' in text
    assert not list(root.rglob('.index.html.*.tmp'))


def test_writes_non_ascii_names_as_utf8(tmp_path):
    root = tmp_path / 'html'
    root.mkdir()
    (root / 'caf\u00e9.txt').write_text('x')
    (root / '\u65e5\u672c\u8a9e.txt').write_text('x')
    generate(root)

    text = (root / 'index.html').read_text(encoding='utf-8')
    assert 'caf\u00e9.txt' in text
    assert '%E6%97%A5%E6%9C%AC%E8%AA%9E.txt' in text


def test_reports_a_root_that_is_not_a_directory(tmp_path):
    target = tmp_path / 'file.txt'
    target.write_text('x')

    result = run_generator(target)

    assert result.returncode == 0
    assert 'is not a directory' in result.stdout
    assert 'Generation complete!' in result.stdout


def test_accepts_an_explicit_root(tmp_path):
    root = tmp_path / 'content'
    root.mkdir()
    (root / 'page.txt').write_text('x')

    result = run_generator(root, cwd=tmp_path)

    assert result.returncode == 0
    assert (root / 'index.html').exists()
